# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-mybanksql
spec:
  selector:
    matchLabels:
      app: mybanksql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mybanksql
    spec:
      containers:
        - image: mysql:8
          name: mybanksql
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Test@123"
            - name: MYSQL_DATABASE
              value: "bankappdb"
          ports:
            - containerPort: 3306
              name: mybanksql
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: my-svc-mybanksql
spec:
  ports:
    - port: 3306
  selector:
    app: mybanksql
---
# Java Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
        - name: bank-app
          image: mskr7/mkadir-bankapp:latest
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mybanksql://my-svc-mybanksql:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Test@123
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bank-app
  name: my-svc-bankapp
  namespace: ns-app
spec:
  type: NodePort
  ports:
    - nodePort: 30006 # The port on the node to expose the service on. match with extraPortMappings containerPort if in kind config
      port: 80 # The port the service is exposed on. can be any port, but 80 is standard for HTTP
      targetPort: 8080 # The port your application is listening on. match with containerPort in deployment.yaml and docker webserver exposed port
  selector:
    app: bank-app
